FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/http-service ./apps/http-service

RUN bun install

RUN bun run db:generate

EXPOSE 3001

CMD [ "bun", "run", "start:backend" ]